### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by ispark323** [hggeorgiev/rails-jwt-auth-tutorial#8]
Hello,
Thank you very much for the tutorial.
I tried downloading Github code and getting an error.
I've put the user through console and when I run the curl to get token, I get following message:

-----

Started POST "/authenticate" for 127.0.0.1 at 2019-02-04 00:34:56 +1100
  ActiveRecord::SchemaMigration Load (0.2ms)  SELECT "schema_migrations".* FROM "schema_migrations"
Processing by AuthenticationController#authenticate as */*
  Parameters: {"email"=>"example@mail.com", "password"=>"[FILTERED]", "authentication"=>{"email"=>"example@mail.com", "password"=>"[FILTERED]"}}
  User Load (0.2ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "example@mail.com"], ["LIMIT", 1]]
  CACHE (0.0ms)  SELECT  "users".* FROM "users" WHERE "users"."email" = ? LIMIT ?  [["email", "example@mail.com"], ["LIMIT", 1]]
Completed 500 Internal Server Error in 186ms (ActiveRecord: 1.2ms)

NoMethodError (undefined method `credentials' for #<ApiApp::Application:0x00000002b65a88>):

lib/json_web_token.rb:4:in `encode'
app/commands/authenticate_user.rb:12:in `call'
app/controllers/authentication_controller.rb:5:in `authenticate'

-----

rails -v : Rails 5.0.6

I'm not sure why Rails.application.credentials is undefined.
Is there something I'm missing?
Thank you.

**Comment by ZakharAntoschenko** [comment]
Hi!
It happened because you use rails 5.0.6, and 'credentials' was added in rails 5.2.0. [here](https://github.com/hggeorgiev/rails-jwt-auth-tutorial/pull/10) i tried to fix that, you can see.

**Comment by hggeorgiev** [comment]
Fixed in #10
